autoload -Uz compinit
# The completion module of Zim will call compinit later.

#
# Zim
#

ZIM_HOME=~/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

#
# Starship
#

eval "$(starship init zsh)"

#
# Pyenv
#

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Remove "/" from WORDCHARS
WORDCHARS=${WORDCHARS/\/}
# Remove "-" from WORDCHARS
WORDCHARS=${WORDCHARS/-}

#
# Enable iTerm2 shell integration
#

if [[ -e ${HOME}/.iterm2_shell_integration.zsh ]]; then
  source ${HOME}/.iterm2_shell_integration.zsh
fi

#
# Aliases
#

alias cdiff="code --diff"
alias gdiff="git diff --no-index"
alias rm="rm -i"
# Neovim required: brew install neovim
alias vim="nvim"
