autoload -Uz compinit
# The completion module of Zim will call compinit later.

#
# History file configuration & History command configuration (copied from Oh My Zsh: https://github.com/ohmyzsh/ohmyzsh/blob/01a955657408c8396fc947075a912ee868d5e2a7/lib/history.zsh)
#

[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000
setopt EXTENDED_HISTORY       # record timestamp of command in HISTFILE
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_IGNORE_DUPS       # ignore duplicated commands history list
setopt HIST_IGNORE_SPACE      # ignore commands that start with space
setopt HIST_VERIFY            # show command with history expansion to user before running it
setopt SHARE_HISTORY          # share command history data

#
# Zim
#

ZIM_HOME=~/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

#
# Starship
#

eval "$(starship init zsh)"

#
# Pyenv
#

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Remove "/" from WORDCHARS
WORDCHARS=${WORDCHARS/\/}
# Remove "-" from WORDCHARS
WORDCHARS=${WORDCHARS/-}

#
# Enable iTerm2 shell integration
#

if [[ -e ${HOME}/.iterm2_shell_integration.zsh ]]; then
  source ${HOME}/.iterm2_shell_integration.zsh
fi

#
# Aliases
#

alias cdiff="code --diff"
alias gdiff="git diff --no-index"
alias rm="rm -i"
# Neovim required: brew install neovim
alias vim="nvim"
